server:
  port: 8080

spring:
  application:
    name: webhook
  # r2dbc
  r2dbc:
    url: r2dbc:postgresql://localhost/poc
    username: pocuser
    password: password
  # webclient related
  codec:
    max-in-memory-size: 1MB

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters

management:
  endpoints:
    web:
      exposure:
        include: metrics,loggers
